name: CI Vulnerable Workflow

env:
  REGISTRY: ghcr.io
  ACTIONS_RUNNER_DEBUG: true  # must not set this!

on:
  push:

jobs:
  build:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        env:
          ACTIONS_STEP_DEBUG: true  # must not set this!
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        env:
          ACTIONS_STEP_DEBUG: true  # must not set this!

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
        env:
          ACTIONS_STEP_DEBUG: true  # must not set this!

      - name: Extract Docker metadata
        uses: docker/metadata-action@v5.7.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
        env:
          ACTIONS_STEP_DEBUG: true  # must not set this!

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        id: build-and-push
        with:
          tags: ${{ steps.meta.outputs.tags }}, ${{ env.REGISTRY }}/${{ github.repository }}:latest
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          ACTIONS_STEP_DEBUG: true  # must not set this!