name: CI Vulnerable Workflow

env:
  REGISTRY: ghcr.io
  ACTIONS_RUNNER_DEBUG: true  # 1. must not set this!

# permissions: {} # 2. we should set default workflow permissions to none

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    # 2. we should MINIMUM set job permissions here
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        env:
          ACTIONS_STEP_DEBUG: true  # 1. must not set this!
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        env:
          ACTIONS_STEP_DEBUG: true  # 1. must not set this!

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
        env:
          ACTIONS_STEP_DEBUG: true  # 1. must not set this!

      - name: Extract Docker metadata
        uses: docker/metadata-action@v5.7.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
        env:
          ACTIONS_STEP_DEBUG: true  # 1. must not set this!

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        id: build-and-push
        with:
          tags: ${{ steps.meta.outputs.tags }}, ${{ env.REGISTRY }}/${{ github.repository }}:latest
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          ACTIONS_STEP_DEBUG: true  # 1. must not set this!

  poutine:
    if: 1 == 0 
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
#################################################################################################
    - name: poutine - GitHub Actions SAST
      uses: boostsecurityio/poutine-action@main # We recommend to use a tagged version and pin it
#################################################################################################
    - name: Upload poutine SARIF file
      uses: github/codeql-action/upload-sarif@4355270be187e1b672a7a1c7c7bae5afdc1ab94a # v3.24.10
      with:
        sarif_file: results.sarif
    
    - name: Upload poutine SARIF file
      run: cat results.sarif